### ISSUE TITLE
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by Dreamer1209** [yael-vinker/CLIPasso#17]
I met an error report when  running the code:
Unexpected error occurred:
 radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal
Traceback (most recent call last):
  File "painterly_rendering.py", line 208, in <module>
    configs_to_save = main(args)
  File "painterly_rendering.py", line 130, in main
    loss.backward()
  File "/home/wyf/anaconda3/envs/py37/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/wyf/anaconda3/envs/py37/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/wyf/anaconda3/envs/py37/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/wyf/anaconda3/envs/py37/lib/python3.7/site-packages/diffvg-0.0.1-py3.7-linux-x86_64.egg/pydiffvg/render_pytorch.py", line 709, in backward
    eval_positions.shape[0])

I have installed all the libraries as required and trained on 2080ti. And I tried to fix it by https://github.com/BachiLi/diffvg/issues/29 but  I failed.
Can anyone help me?

**Comment by Dreamer1209** [comment]
i update my pytorch from 1.7.1 to 1.9.1 and fix the problem...TAT
